"""Add profile fields to User

Revision ID: 09945ef530ea
Revises: f565e6776b0b
Create Date: 2026-07-27 12:09:29.955130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09945ef530ea'
down_revision = 'f565e6776b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_picture_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))
        batch_op.add_column(
            sa.Column(
                'sms_marketing_consent', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(sa.Column('sms_consent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text('now()'),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sms_consent_at')
        batch_op.drop_column('sms_marketing_consent')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('oauth_picture_url')

    # ### end Alembic commands ###
