"""Add newsletter subscribers

Revision ID: 17edde27f229
Revises: 09945ef530ea
Create Date: 2026-07-27 16:00:55.582619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17edde27f229'
down_revision = '09945ef530ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_subscribers_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscribers_email'))

    op.drop_table('newsletter_subscribers')
    # ### end Alembic commands ###
