"""Add job_posts and ip_locations tables

Revision ID: 3f714742fc3e
Revises: 5bf099ccd132
Create Date: 2026-07-31 09:08:37.288805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f714742fc3e'
down_revision = '5bf099ccd132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('looked_up_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_locations_ip_address'), ['ip_address'], unique=True)

    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=170), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('job_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_posts_posted_by_id'), ['posted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_posts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posts_status'))
        batch_op.drop_index(batch_op.f('ix_job_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_job_posts_posted_by_id'))

    op.drop_table('job_posts')
    with op.batch_alter_table('ip_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_locations_ip_address'))

    op.drop_table('ip_locations')
    # ### end Alembic commands ###
