"""Add villages, village_landmarks and village_photos tables

Revision ID: 49579c28c0dc
Revises: a2ef6f3f842d
Create Date: 2026-07-31 19:28:06.750322

"""

import json
import os
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49579c28c0dc"
down_revision = "a2ef6f3f842d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "villages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("taluka", sa.String(length=60), nullable=False),
        sa.Column("district", sa.String(length=60), nullable=False),
        sa.Column("gram_panchayat", sa.String(length=150), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("population_source", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("villages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_villages_district"), ["district"], unique=False)
        batch_op.create_index(batch_op.f("ix_villages_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_villages_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_villages_taluka"), ["taluka"], unique=False)

    op.create_table(
        "village_landmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("submitted_by_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["villages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("village_landmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_village_landmarks_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_village_landmarks_submitted_by_id"), ["submitted_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_village_landmarks_village_id"), ["village_id"], unique=False
        )

    op.create_table(
        "village_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("submitted_by_id", sa.Integer(), nullable=False),
        sa.Column("caption", sa.String(length=255), nullable=False),
        sa.Column("image", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["village_id"],
            ["villages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("village_photos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_village_photos_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_village_photos_submitted_by_id"), ["submitted_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_village_photos_village_id"), ["village_id"], unique=False
        )

    # ### end Alembic commands ###

    # Seed the village directory from the Census of India village listings
    # (see app/data/goa_villages.json for provenance notes). Population is
    # deliberately left null here -- there is no reliable government API for
    # it, so it is filled in later via admin edits / community submissions.
    villages_table = sa.table(
        "villages",
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("taluka", sa.String),
        sa.column("district", sa.String),
        sa.column("gram_panchayat", sa.String),
        sa.column("category", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    data_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "app", "data", "goa_villages.json"
    )
    with open(data_path, encoding="utf-8") as f:
        villages = json.load(f)

    now = datetime.now(timezone.utc)
    op.bulk_insert(
        villages_table,
        [
            {
                "name": v["name"],
                "slug": v["slug"],
                "taluka": v["taluka"],
                "district": v["district"],
                "gram_panchayat": v["gram_panchayat"],
                "category": v["category"],
                "created_at": now,
                "updated_at": now,
            }
            for v in villages
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("village_photos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_village_photos_village_id"))
        batch_op.drop_index(batch_op.f("ix_village_photos_submitted_by_id"))
        batch_op.drop_index(batch_op.f("ix_village_photos_status"))

    op.drop_table("village_photos")
    with op.batch_alter_table("village_landmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_village_landmarks_village_id"))
        batch_op.drop_index(batch_op.f("ix_village_landmarks_submitted_by_id"))
        batch_op.drop_index(batch_op.f("ix_village_landmarks_status"))

    op.drop_table("village_landmarks")
    with op.batch_alter_table("villages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_villages_taluka"))
        batch_op.drop_index(batch_op.f("ix_villages_slug"))
        batch_op.drop_index(batch_op.f("ix_villages_name"))
        batch_op.drop_index(batch_op.f("ix_villages_district"))

    op.drop_table("villages")
    # ### end Alembic commands ###
