"""add site_visits table

Revision ID: 588cd8ac87b3
Revises: 17edde27f229
Create Date: 2026-07-30 22:03:15.918462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588cd8ac87b3'
down_revision = '17edde27f229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_visits_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_visits_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_visits_visited_at'), ['visited_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_visits_visited_at'))
        batch_op.drop_index(batch_op.f('ix_site_visits_user_id'))
        batch_op.drop_index(batch_op.f('ix_site_visits_ip_address'))

    op.drop_table('site_visits')
    # ### end Alembic commands ###
