"""Add wikipedia cache fields to villages

Revision ID: 6f60b6c3ccbb
Revises: 49579c28c0dc
Create Date: 2026-08-08 17:24:06.671275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f60b6c3ccbb'
down_revision = '49579c28c0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wiki_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wiki_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wiki_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('wiki_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wiki_image_attribution', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('wiki_image_source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('wiki_checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.drop_column('wiki_checked_at')
        batch_op.drop_column('wiki_image_source_url')
        batch_op.drop_column('wiki_image_attribution')
        batch_op.drop_column('wiki_image')
        batch_op.drop_column('wiki_url')
        batch_op.drop_column('wiki_history')
        batch_op.drop_column('wiki_summary')

    # ### end Alembic commands ###
