"""Add stories table

Revision ID: eed11583567e
Revises: 7a2c1e9d4f3b
Create Date: 2026-07-31 10:12:56.563730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed11583567e'
down_revision = '7a2c1e9d4f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=170), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_stories_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_status'))
        batch_op.drop_index(batch_op.f('ix_stories_slug'))
        batch_op.drop_index(batch_op.f('ix_stories_author_id'))

    op.drop_table('stories')
    # ### end Alembic commands ###
