"""add businesses table

Revision ID: f1150266a1a0
Revises: 588cd8ac87b3
Create Date: 2026-07-30 22:11:39.418814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1150266a1a0'
down_revision = '588cd8ac87b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=170), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('nation', sa.String(length=30), nullable=False),
    sa.Column('postcode_district', sa.String(length=10), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_status'))
        batch_op.drop_index(batch_op.f('ix_businesses_slug'))
        batch_op.drop_index(batch_op.f('ix_businesses_owner_id'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
